defaultSemverRangePrefix: ""

enableTelemetry: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error
  - code: YN0066
    level: error

nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/git-hooks.cjs
    spec: "git-hooks"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
