markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - search
repo_name: oliversalzburg/node-scripts-docs
repo_url: https://github.com/oliversalzburg/node-scripts-docs
site_name: Node Scripts Docs
theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  name: material
